dist: trusty
sudo: required
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io

script:
  - docker build -t sshaaf/mailcatcher:$TRAVIS_COMMIT .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag sshaaf/mailcatcher:$TRAVIS_COMMIT quay.io/sshaaf/mailcatcher:$TAG
  - docker push quay.io/sshaaf/mailcatcher:$TAG